// Signup tests

// Success
POST http://localhost:3000/api/users/signup
Content-Type: application/json
{
    "email": "alex@email.com",
    "password": "apple123"
}

// Failure - email address taken
POST http://localhost:3000/api/users/signup
Content-Type: application/json
{
    "email": "alex@email.com",
    "password": "apple123"
}

// Failure - invalid email address
POST http://localhost:3000/api/users/signup
Content-Type: application/json
{
    "email": "alex.com",
    "password": "apple123"
}

// Failure - password not long enough
POST http://localhost:3000/api/users/signup
Content-Type: application/json
{
    "email": "bob@email.com",
    "password": "apple12"
}

// Failure - password contains 'password'
POST http://localhost:3000/api/users/signup
Content-Type: application/json
{
    "email": "bob@email.com",
    "password": "password123"
}

// Login success
POST http://localhost:3000/api/users/login
Content-Type: application/json
{
    "email": "alex@email.com",
    "password": "apple123"
}

// Login failure - incorrect email
POST http://localhost:3000/api/users/login
Content-Type: application/json
{
    "email": "user@email.com",
    "password": "apple123"
}

// Login failure - incorrect password
POST http://localhost:3000/api/users/login
Content-Type: application/json
{
    "email": "alex@email.com",
    "password": "apple12"
}